# Generated by Django 4.2 on 2024-03-11 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=30)),
                ('deadline', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('suggested_time1', models.DateTimeField(blank=True, null=True)),
                ('suggested_time2', models.DateTimeField(blank=True, null=True)),
                ('suggested_time3', models.DateTimeField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('preferred_user', models.BooleanField()),
                ('preferred_contact', models.BooleanField()),
                ('meeting_status', models.CharField(choices=[('Unconfirmed', 'Unconfirmed'), ('Scheduling', 'Scheduling'), ('Confirmed', 'Confirmed')], default='Unconfirmed', max_length=11)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to='contacts.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_meetings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
