# Generated by Django 4.2 on 2024-03-11 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='preferred_user',
        ),
    ]
