# Generated by Django 5.0.2 on 2024-04-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_remove_availabilitycontactblock_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityblock',
            name='availability_level',
            field=models.CharField(choices=[('preferred', 'Preferred'), ('lesspreferred', 'Less Preferred'), ('none', 'none')], max_length=20),
        ),
    ]
