# Generated by Django 5.0.4 on 2024-04-07 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
        ('meeting', '0002_alter_meeting_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilitycontactblock',
            name='contact',
        ),
        migrations.AddField(
            model_name='availabilitycontactblock',
            name='meeting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contact_block', to='meeting.meeting'),
            preserve_default=False,
        ),
    ]
